Neos:
  Neos:
    fusion:
      autoInclude:
        NEOSidekick.HtmlContent: true
    userInterface:
      translation:
        autoInclude:
          NEOSidekick.HtmlContent:
            - 'Fusion/*'
            - 'NodeTypes/*'
  Fusion:
    defaultContext:
      NEOSidekickHtmlContent: 'NEOSidekick\HtmlContent\Eel\Helper'
